ans = """BWBWBWBWBWBWBWBWBWBWBWBWB--WBWBWBWBWBWBWBWBWB-BWBW

WBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWB-BWBWB

BW-WBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW-WBWBWBWBW

WBWBWBWBWBWBWBWBWBWBWBWBWBW-WBWBWBWBWBWBWBWBWBWBWB

BWBWBWBW-WBWBWBWBWBWBWBWBWBWBW-WBWBWBWBWBWBWBWBWBW

WBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWB

BWBWBWB-BWBWBW-WBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW

WBW-WBWBWBWBWBWBWBWBWB-BWBWBWBWBWBWBWBWBWBWBWB-BWB

BWBWB-BWBWBW-WBWBWBWBWBWBWBWBWBWBWBWBWBWBWBW-WBWBW

WBW-WBWBWBWBWBWBWBWB-BWB-BWBWBWBWBWBWBWBWBW..."""

output = """WBWBWBWBWBWBWBWBWBWBWBWBW--WBWBWBWBWBWBWBWBWB-WBWB

BWBWBWBWBWBWBWBWBWBWBWBWBWB.WBWBWBWBWBWBWBWB-WBWBW

WB-BWBWBWBWBWBWBWBWBWBWBWBWB.WBWBWBWBWBW-WBWB.WBWB

BWBWBWBWBWBWBWBWBWBWBWBWBWB-WBWBWBWBWBWBWBWBWB.WBW

WBWBWBWB-BWBWBWBWBWBWBWBWBWB.W-WBWBWBWBWBWBWBWB.WB

BWBWBWBWBWBWBWBWBWBWBWBWBWBWB.WBWBWBWBWBWBWBWBWB.W

WBWBWBW-WBWBWB-BWBWBWBWBWBWBWB.WBWBWBWBWBWBWBWBWB.

BWB-BWBWBWBWBWBWBWBWBW-WBWBWBWB.WBWBWBWBWBWBWB-BWB

WBWBW-WBWBWB-BWBWBWBWBWBWBWBWBWB.WBWBWBWBWBW-WBWBW

BWB-BWBWBWBWBWBWBWBW-WBW-WBWBWBWB.WBWBWBWBW..."""

count_ans = 0
count_output = 0

for c in ans:
    if c=='W' or c =='B':
        count_ans += 1


for c in output:
    if c=='W' or c =='B':
        count_output += 1

print(count_ans)
print(count_output)